css/style.css
index.html

Fixed footer margins.

---

css/style.css

Changed the left border color of the cards in welcome section to match the section border.

Suggested color change in welcome cards to match section-color.

---

index.html

Partial resolution to issue #101 .

Fixed "highlight" typo.

---

index.html

Tested locally. Resolves issue #92 .

Fixed github link by using an alias for the url.

---

index.html

Tested locally and operational. Resolves issue #91 .

Fixed hamburger menu. It is now operational.

---

index.html

Switch to Facebook video.

---

index.html

Clean up PGP section. Fixes #101

---

css/style.css
index.html
resources/banter/index.html

Please also remove olinalumni.org/banter -- not exactly sure how that is hosted.

Add /resources/banter with introduction and faq.

---

resources/banter/index.html

Greg, please merge this in ASAP -- we sent an email to all alumni in error, and are pointing them to this website.

message because email went out too broadly

---

index.html
tags/card-list.tag

Adds social media embeds, updates accounts.

---

resources/banter/css/banterstyle.css
resources/banter/index.html

Wkd banter 2019

---

resources/banter/index.html

Hey, this is the banter update for 2020. 
Updates include:
- About Banter 
- Timeline
- Survey Links
- FAQ
- Email

Banter update 2020

---

resources/banter/index.html

Hey, I had the CSS class incorrectly for mobile so this is the fix.

Banter date update for mobile

---

resources/banter/index.html

Hey, after talking to Shannon we would like to update the dates so here is a PR.

Signup timeline adjusted

---

resources/banter/index.html

Fixed mobile dates

---

resources/banter/index.html

I would like to track which medium is getting the best response rates for alumni and students.

Adding Google analytics for Banter

---

resources/banter/index.html

mentor selection survey updated for 2020-2021

Update survey url

---

resources/banter/index.html

Forgot to update the mobile link

Update Banter mobile link

---

resources/holidaygiftexchange/index.html

Reverts olinalumni/olinalumni.github.io#156

Revert "updated logistics"

---

resources/banter/index.html

This updates the dates and survey links for the 2021-2022 Banter cycle.

Update Banter dates for 2021-2022

---

resources/banter/index.html

Seeing if changing URLs from absolute to relative URLs fixes anything...

Seeing issues with the site certificate when loading CSS stylesheet
